export const UPDATE_COMMENT_TOPIC = 'UPDATE_COMMENT_TOPIC';
export const DELETE_COMMENT_TOPIC = 'DELETE_COMMENT_TOPIC';
export const ADD_COMMENT_TOPIC = 'ADD_COMMENT_TOPIC';
export const ADD_COMMENT_SUCCESS = 'Successfully add a comment';
export const DELETE_COMMENT_SUCCESS = 'Successfully delete a comment';
export const DELETE_COMMENT_FAIL = 'Cannot delete a post comment';
export const COMMENT_NOT_FOUND = 'Cannot find the comment'
export const UPDATE_COMMENT_SUCCESS = 'Successfully update a comment';
export const UPDATE_COMMENT_FAIL = 'Cannot update a post comment';
export const ADD_COMMENT_FAIL = 'Cannot add a post comment'